aliases:
  fleeks: cd ~/.local/share/fleek
  nfleek-apply: nix run github:ublue-os/fleek -- apply
allow_broken: false
bling: default
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
  autocommit: true
  autopull: true
  autopush: true
  enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
  - helix
  - neofetch
  - jq
paths:
  - $HOME/bin
  - $HOME/.local/bin
  - /usr/local/bin # for fleek itself on nixos, and brew on intel macs
  - /opt/homebrew/bin # for brew on arm macs
programs:
  - dircolors
shell: bash
systems:
  - arch: x86_64
    home: ""
    hostname: ubunix
    os: linux
    username: daniel
  - arch: aarch64
    home: ""
    hostname: ubunixarm
    os: linux
    username: daniel
  - arch: aarch64
    home: ""
    hostname: nixos
    os: linux
    username: daniel
  - arch: aarch64
    home: ""
    hostname: macnix.imetrical.com
    os: darwin
    username: daniel
track: nixos-unstable
unfree: true
users:
  - email: daniel.lauzon@gmail.com
    name: daniel
    ssh_private_key_file: ""
    ssh_public_key_file: ""
    username: daniel
